51 todo setting up todo list canvas
cse110-sp24-group30/cse110-sp24-group30 pull request #64
Opened 2024-05-31 18:18 UTC by ChooChooChao

Objectives
- Set up the HTML page for the Todo List canvas

Acceptance Criteria
- [x ] Set up the 3 columns with a few dummy tasks hard coded
- [x ] Set up page title
- [x ] Include the dashboard headers with navigation to other pages

2024-05-31 22:07 UTC, shjucsd requested changes
The css looks good. For the hard-coded data, can we have the number of tasks display for in progress and done as well just so that we are consistent with the ui? Similarly, can you add the tags for different labels like Work, Personal.

2024-06-02 05:22 UTC, alt012ucsd approved these changes
Everything looks good, all base functionality accounted for.

2024-06-02 05:51 UTC, shjucsd approved these changes
I added the functionality for updating the localStorage on adding and deleting the tasks and dynamically updating the display count as well, i also updated the formatting using prettier

2024-06-04 21:36 UTC, adironene requested changes
Amazing work! Good job dividing the tasks up in different functions. Just left a few comments for suggestions and good practice.

Also **todo** - please attach a video for UI demo

2024-06-04 21:36 UTC, adironene commented on to_do/to-do-app.js
> +    console.log("existing");
if we are logging stuff in console, I would make it more detailed. Like existing what? + more context

2024-06-04 21:36 UTC, adironene commented on to_do/to-do.html
> +                            <!-- <div class="buttons">
remove unused comments

2024-06-04 21:36 UTC, adironene commented on to_do/to-do-app.js
> +function addTask(toDoContainer, existing, category) {
I would add a bit more comments throughout the doc to tell the reader what the code is doing. It's self-explanatory after reading through a few times but having comments before each "group" of tasks would be very helpful!

2024-06-04 23:04 UTC, kabirsachdev7 approved these changes
Foundation for the backend is good. Definitely meets the acceptance criteria. Phoebe touched on some points already, but just want to say to add more comments pls wherever you can as you continue building the todo.

2024-06-05 00:03 UTC, shjucsd commented
for the logging into the console comment, i think we just had those to check our implementation before and that the code was entering the correct places, we can remove them and i can add comments for all the functions so that they can be used to create jsdocs

2024-06-05 00:52 UTC, adironene approved these changes
Fixes look good!

2024-06-05 00:53 UTC, merged